In [1]:
import numpy as np

In [2]:
array_a = np.array([1,2,3])


In [3]:
array_a

array([1, 2, 3])

In [4]:
array_b = np.array([[1,2,3],[4,5,6]])
print(array_b)

[[1 2 3]
 [4 5 6]]


In [5]:
array_hw_1 = np.array([4,5,7,10])

In [6]:
array_hw_1

array([ 4,  5,  7, 10])

In [7]:
array_hw_2 = np.array([[4,5],[7,10]])

In [8]:
array_hw_2

array([[ 4,  5],
       [ 7, 10]])

In [9]:
np.mean(array_hw_1)

6.5

In [10]:
np.mean(array_hw_2)

6.5

In [11]:
np.mean(array_hw_1)

6.5

In [12]:
np.mean(array_hw_2)

6.5

In [13]:
np.mean(array_hw_2, axis = 1)

array([4.5, 8.5])

In [14]:
np.mean(array_hw_2, axis = 0)

array([5.5, 7.5])

In [15]:
np.mean(array_hw_2, axis = 0, dtype = np.int)

C:\Users\User\AppData\Local\Temp\ipykernel_11324\1210526769.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.mean(array_hw_2, axis = 0, dtype = np.int)


array([5, 7])